console version of darts
OlegStrelnikov087/Darts0 pull request #1
Opened 2024-11-26 20:56 UTC by OlegStrelnikov087

2024-12-02 21:42 UTC, yandexHas requested changes
Нужно все исправить

2024-12-02 21:42 UTC, yandexHas commented on src/index.js
> +let start = new StartGame()
если объект не пересоздаешь, то лучше делать const

2024-12-02 21:42 UTC, yandexHas commented on src/index.js
> -document.querySelector('.play').addEventListener('click', ()=>{
нельзя забывать про обратную операцию - removeEventListener, подумай как лучше это сделать

2024-12-02 21:42 UTC, yandexHas commented on src/index.js
>  })
всю инициализацию надо:
а) вынести в отдельную функцию или класс
б) делать по событию полной загрузки документа, дождавшись 100% загрузки html страницы

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +export default class Actions {
лучше использовать именованный экспорт, а не дефолтный

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +    getMoveResult(player, moveNumber) {
move это движение, тут мы никуда не двигаемся. Попробуй подобрать более корректное слово для "ход"

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +        let scores = ''
у тебя scores не используется за пределами do while, тогда зачем он здесь? внеси его внутрь цикла и через const

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +    getMoveResult(player, moveNumber) {
и, может быть, здесь так же скорее не result, а что-то типа points?

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +                    if (Number(number)) {
у тебя ниже несколько раз используется приведение number к числу. Это расточительно и ухудшает читабельность кода. Да еще и название переменной number, под которым ожидаешь число, а по факту строка, причем не факт что валидная (что будет, если введут "T345gd" ?
сделай сразу приведение к числу и работай с этой переменной сразу как с числовой

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +                        if (parseInt(number) <= 20) {
Почему где то Number(number), а где-то parseInt(number) ?

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +                            scoresQuantity = NaN
зачем присваивать что-то непонятное в переменную, чтобы просто выйти из цикла, чтобы потом все равно вернуть это что-то непонятное как результат функции? не проще и надежнее сделать сразу return NaN?

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +        if (result > 1 || (result === 0 && doubling === 'double')) {
второе условие лишнее, ты то же самое проверяешь в той функции, где это вызываешь. Двойная работа и опасность ошибок из-за дублирования кода

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/actions.js
> +            alert('error Перебор')
если у тебя calculateScores, то она не должна делать ничего кроме подсчета очков. Никакого вывода сообщений быть не должно

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/game.js
> +let actionsClass = new Actions()
почему let?

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/game.js
> +    while (gameOver != true) {
как досрочно прекратить игру?

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/game.js
> +            if (gameOver != true) {
у тебя в 6й строке такое же условие, это очень плохое решение. Подумай как избежать этого дублирования

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/game.js
> +                for (let moveNumber = 1; moveNumber < 4; moveNumber++) {
4 это паттерн магическое число (почитай в инете). Вынеси его за пределы класса в виде константы пока

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/game.js
> +                            player.wins +=1
а можно просто написать player.wins++ :)

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/start.js
> +        let playersName = []
const

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/start.js
> +        while (createPlayers != false) {
while (createPlayers) {...

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/start.js
> +            let name = prompt('Введите имя игрока')
данная функция ничего не должна знать о prompt, она должна вызвать какую-то чужую, которая уже знает с каким интерфейсом работаем

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/start.js
> +                createPlayers = false
здесь достаточно просто сделать break

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/start.js
> +        } while (isNaN(roundsQuantity))
не, плохое решение проверять выход из цикла по isNaN (было бы неплохо, если бы ты ориентировался на isNaN в случае именно преобразования ввода пользователя, а иначе надо сделать просто выход по понятному условию (например ввод пустой строки))

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/start.js
> +            scores = prompt('Введите количество очков')
аналогично все

2024-12-02 21:42 UTC, yandexHas commented on src/public/js/start.js
> +        let players = []
подумай как всю функцию лаконичнее сделать через методы массива

2024-12-24 14:46 UTC, OlegStrelnikov087 commented on src/public/js/game.js
> +    while (gameOver != true) {
сейчас все сделал по другому, добавил отдельный метод завершения игры, туда можно будет добавить любое условие завершения игры помимо выигрыша игрока

2025-01-10 12:50 UTC, yandexHas commented on src/public/js/startData.js
> +export const startData = class StartData {
так лучше не делать. Лучше сделать так:
```suggestion
class StartData {
.....
}

export const startData = new StartData()
```

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/startData.js
> +export const startData = class StartData {
а у тебя в index.js еще есть const startData = ....   дубль?

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/startData.js
> +    getPlayersName() {
если методы снаружи не используются, то добавь модификатор видимости (private/protected)

2025-01-13 17:21 UTC, yandexHas commented on src/index.js
> +    })
зачем 2 раза один и тот же обработчик вызывать? он же и срабатывать будет два раза на каждый клик. По идее сделать лучше так:
- на событие полной загрузки контента делаем создание объекта игры, вызываем в нем некий метод startGame()
- внутри startGame перед циклом игры вешаем все обработчики, после цикла удаляем обработчики

в этом случае у нас конкретно по месту будут корректно обрабатываться обработчики

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/actions.js
> +export const actions = class Actions {
аналогично, так делать не надо

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/actions.js
> +                const number = parseInt(numberArr.join(''))
тут надо убедиться, что ввели действительно число и оно корректно получено

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/actions.js
> +                if (number <= 20) {
константа 20 это паттерн "магическое число", почитай про это. И оно используется у тебя несколько раз (строка 13, строка 18, надо вынести ее в константы и использовать константой

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/actions.js
> +                    alert('error! Нужно ввести только число от 0 до 20, для утроения используйте t или T в начале строки, для удвоения w или W');
а пустое число если ввести, то что будет?

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/actions.js
> +            scores = prompt(`Результат ${moveNumber}-го броска игрока ${player.name}`)
а зачем в 10й строке кладем в переменную пустое значение, если следом же туда кладем значение из промпта?

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/game.js
> +const actionsClass = new actions()
это лучше внести в класс мне кажется

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/game.js
> +        // можно добавить еще варианты завершения игры
если используешь фигурные скобки для скоупа условия, то используй их и для альтернативного скоупа условия. Но в целом код функции у тебя бесполезный, по факту этот код выглядит так:
```javascript
gameOver(playerWin) {
  return playerWin;
}
```

ну и если ты возвращаешь булево значение, то именовать функцию принято с префиксом isGameOver или hasGameOver

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/startData.js
> +            if (name!= ''){
```suggestion
            if (name != ''){
```
всегда разделяй знаки операций и сравнения пробелом с обеих сторон

2025-01-13 17:21 UTC, yandexHas commented on src/public/js/startData.js
> +}
72-74 строки - не нужно столько пустых строк, следи всегда за форматированием и чистотой кода

2025-01-29 14:42 UTC, yandexHas commented on src/index.js
> +    //     }
комменты кода перед пушем надо удалять, мусора быть не должно

2025-01-29 14:42 UTC, yandexHas commented on src/index.js
> +    function listener(event){
функция внутри функционального блока это плохо.  Либо опиши ее через переменную типа 
``const listener = (event) { .... }``

2025-01-29 14:42 UTC, yandexHas commented on src/public/js/actions.js
> +            if (scoresQuantity <= THROW_LIMIT) {
а если введут 50, то что будет?

2025-01-29 14:42 UTC, yandexHas commented on src/public/js/actions.js
> +                const number = parseInt(numberArr.join(''))
не вижу ответа на коммент

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/index.js
> +    })
исправил, немного по своему правда, подскажешь норм вариант или  фигня

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/public/js/actions.js
> +            scores = prompt(`Результат ${moveNumber}-го броска игрока ${player.name}`)
убрал

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/public/js/actions.js
> +                if (number <= 20) {
вынес

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/public/js/actions.js
> +                const number = parseInt(numberArr.join(''))
так у меня же ниже проверка если это NaN то выводится сообщение об ошибке  и ввод запрашивается еще раз ввод количества очков, или просто лучше именно сразу проверять? Просто много раз проверял, ошибок не было именно по подсчетам и вводу очков с броска

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/public/js/actions.js
> +                    alert('error! Нужно ввести только число от 0 до 20, для утроения используйте t или T в начале строки, для удвоения w или W');
вывод сообщения о том что надо ввести только число от 0 до 20, t и w для утроений и удвоений, запросится повторный ввод количества набранных очков за бросок

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/public/js/startData.js
> +}
почистил

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/public/js/startData.js
> +            if (name!= ''){
есть

2025-01-29 14:48 UTC, OlegStrelnikov087 commented on src/index.js
> -document.querySelector('.play').addEventListener('click', ()=>{
сделал

2025-01-29 14:50 UTC, yandexHas commented on src/public/js/actions.js
> +                const number = parseInt(numberArr.join(''))
так у тебя не будет NaN если ввести 50

2025-01-29 14:54 UTC, yandexHas commented on src/public/js/game.js
> +        while (gameIsOver === false) {
в условиях всегда лучше проверять на истину и соотв переменные называть так, чтобы в проверке на истину имя переменной говорило "да", например:
```
       let gameNotIsOver = true
        while (gameNotIsOver) {
```

2025-01-29 14:54 UTC, yandexHas commented on src/public/js/startData.js
> +    #getPlayers(playersName, score) {
решетку рекомендуется использовать для модификаторов в переменных класса, а для методов класса лучше писать явно private/protected

2025-01-29 17:55 UTC, OlegStrelnikov087 commented on src/public/js/game.js
> +        while (gameIsOver === false) {
понял, сделал

2025-01-29 17:56 UTC, OlegStrelnikov087 commented on src/public/js/actions.js
> +            if (scoresQuantity <= THROW_LIMIT) {
изменил метод, сейчас по чище по понятнее

2025-01-29 17:59 UTC, OlegStrelnikov087 commented on src/index.js
> +    function listener(event){
понял, исправил

2025-02-09 18:42 UTC, merged